/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "MainWindow.h"
#include "../Builds/VisualStudio2008/MainComponent.h"
#include "../Builds/VisualStudio2008/FileIO.h"

FileIO *file;

//@TODO: add the output to file data
//==============================================================================
MainAppWindow::MainAppWindow()
    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                      Colours::lightgrey,
                      DocumentWindow::allButtons)
{
	//read in all the info
	file = new FileIO();
	file->readFile();
	
	//create the main component and show
	MainComponent *window = new MainComponent(file->getAccountsList());
	window->setBounds(0,0,600,400);
	setContentOwned(window,true);
    centreWithSize (500, 400);
    setVisible (true);
}//end constructor

//destructor
MainAppWindow::~MainAppWindow()
{
}//end destructor

//close the window
void MainAppWindow::closeButtonPressed()
{
	file->outputFiles();
    JUCEApplication::getInstance()->systemRequestedQuit();
}//end method closeButtonPressed
